### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CokkocZateki** [drkthunder02/phptimerboard#2]
Hi.

Im trying to access the site on my server. however each time i login i get 
`{"error":"invalid_request","error_description":"The callback URI doesn't match the value stored for this client"}`

im sure my config is correct except for the useragent. what is suppose to go there
https://github.com/drkthunder02/phptimerboard/blob/master/functions/configuration/config.ini#L5

Thank you in advance

**Comment by drkthunder02** [comment]
Did you go to http://developers.eveonline.com and register the application?  Once you register the application with CCP they will give you a client id and secret key.  The useragent should be changed to something that denotes your specific site.

**Comment by drkthunder02** [comment]
Also note the callback uri when you register the application should be something like http://<sub-domain>.<domain>.com/index.php

**Comment by CokkocZateki** [comment]
ahh okay. after changing the url manually i got thru. however the error started with the install.php file

**Comment by drkthunder02** [comment]
I have changed how installation is handled but it's still a work in
progress. The newest version has some changes and moves it to a function
rather than a separate file. Try the newer version by downloading the
latest version and using it. If it doesn't work still I can tell you what
you need to manually edit in the tables to make it work correctly.

On Apr 21, 2017 5:54 AM, "CokkocZateki" <notifications@github.com> wrote:

ahh okay. after changing the url manually i got thru. however the error
started with the install.php file

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/drkthunder02/phptimerboard/issues/2#issuecomment-296160736>,
or mute the thread
